### ISSUE TITLE
Review Ticket #1 | Valen Reynolds

### ISSUE THREAD

**Issue by ValenReynolds** [TristanCopley/photoboard#2]
Scrum Team GitHub pages (2 points)

Web Project: Project Description, Project Plans/Ideas/Wires, Time box
Team Roles described, Project Owner or Sponsor described, Scrum Board started
Individual GitHub pages (3 points)

GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on [cspcoders (Links to an external site.)](https://cspcoders.nighthawkcodingsociety.com/))
GitHub page that documents Data Structures project, using code snippets for key learnings, and links to  GitHub for code and Replit for runtime
GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime

**Comment by VidhiKulkarni** [comment]
**Overall Score: 2/3**

Github page with notes and actions on Jekyll Completed (1/1)
Replit/code on Github page not finished (0/1)
Github page on Jekyll documenting Create Task (1/1)
