### ISSUE TITLE
Review Ticket #1 | Tristan Copley

### ISSUE THREAD

**Issue by TristanCopley** [TristanCopley/photoboard#4]
Individual GitHub pages (3 points)

- [x] GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on [cspcoders (Links to an external site.)](https://cspcoders.nighthawkcodingsociety.com/))

- [x] GitHub page that documents Data Structures project, using code snippets for key learnings, and links to GitHub for code and [Replit](https://replit.com/join/bkchvhqase-tristancopley) for runtime

- [x] GitHub page that documents intended [Create Task](https://github.com/JakubPonulak/5_hackers/wiki/Create-Task:-Tristan) project for College Board, snippets, and links to Runtime

https://tristancopley.github.io/tri3self/

**Comment by shreya-ahujaa** [comment]
**Overall Score: 2.7/3**
- Github Page with Notes and TPT Notes/Actions: 1/1
- Replit Challenges are mostly completed
    - -0.3 for no animation   
- Create Task Plan for College Board: 1/1
