### ISSUE TITLE
Review Ticket #2 | Tristan Copley

### ISSUE THREAD

**Issue by TristanCopley** [TristanCopley/photoboard#9]
- [x] GitHub page for Test Prep study, requiring 5.3, 5.4 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on [cspcoders](https://cspcoders.nighthawkcodingsociety.com/)).

GitHub page that documents key learnings and code snippets using GitHub and replit.

- [x] InfoDB lists

- [x] InfoDB loops

- [x] Fibonacci

**Comment by Reinhardtlotter** [comment]
3/3 All requirements hit and good originality with code.
